set foreign_key_checks=0;
drop table if exists campus cascade;
drop table if exists dept_group cascade;
drop table if exists appointment cascade;
drop table if exists department cascade;
drop table if exists person cascade;
drop table if exists Campus cascade;
drop table if exists ContactAppointment cascade;
drop table if exists Department cascade;
drop table if exists MemberAppointment cascade;
drop table if exists PPerson_Role cascade;
drop table if exists PendingPerson cascade;
drop table if exists Person cascade;
drop table if exists Person_Role cascade;
drop table if exists Role cascade;
drop table if exists migrations cascade;
drop table if exists password_resets cascade;
drop table if exists Person_Department cascade;
drop table if exists PPerson_Department cascade;
drop table if exists personal_access_tokens cascade;
drop table if exists users;
drop table if exists User;
drop table if exists model_has_permissions;
drop table if exists model_has_roles;
drop table if exists permissions;
drop table if exists role;
drop table if exists role_has_permissions;
drop view if exists dept_person_view cascade;
drop view if exists person_role_view cascade;
drop view if exists dept_contact_view cascade;
set foreign_key_checks=1;
